/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/audit/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["audit_logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 本地自举端点：返回 admin token（供前端 P1 接入鉴权） */
        get: operations["bootstrap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/client/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["client_disconnect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/client/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["client_send"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_clients"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["event_add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["event_remove"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["event_toggle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["event_update"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["export_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["import_config"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logs_clear"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/persisted": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 历史持久化日志分页查询（P1-4）：SQLite 全量 + 过滤 + 分页 */
        get: operations["get_logs_persisted"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mock/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["mock_add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mock/get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["mock_get"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mock/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["mock_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mock/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["mock_remove"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mock/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["mock_start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mock/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["mock_stop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mock/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["mock_update"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scene/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 新增场景（自动生成 id / 时间戳并持久化） */
        post: operations["scene_add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scene/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 场景列表 */
        get: operations["scene_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scene/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 删除场景（仅移除编排，不停服务） */
        post: operations["scene_remove"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scene/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 一键启动场景：按 server_ids 顺序启动，返回逐服务结果 */
        post: operations["scene_start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scene/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 一键停止场景：逆序停止，返回停止数 */
        post: operations["scene_stop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scene/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 更新场景 */
        post: operations["scene_update"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/send-message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["send_message"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/server/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["server_add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/server/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_server_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/server/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["server_remove"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/server/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["server_restart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/server/restart-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["server_restart_all"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/server/runtimes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_server_runtimes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/server/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["server_start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/server/start-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["server_start_all"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/server/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["server_stop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/server/stop-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["server_stop_all"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/server/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["server_update"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_servers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_settings"];
        put?: never;
        post: operations["save_settings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description API 标准响应（与现网 `{ success, data?, errorCode?, error?, message?, timestamp }` 对齐） */
        ApiResponse_Value: {
            data?: unknown;
            error?: string | null;
            errorCode?: string | null;
            message?: string | null;
            success: boolean;
            timestamp: string;
        };
        /** @description 单条审计记录 */
        AuditEntry: {
            /** @description 操作名：server_start / server_update / mock_remove ... */
            action: string;
            /** @description 操作者：admin / viewer / local（鉴权关闭或自举时） */
            actor: string;
            /** @description 附加详情（JSON） */
            detail?: unknown;
            id: string;
            /** @description 结果：success / failure */
            result: string;
            targetId?: string | null;
            /** @description 对象类型：server / mock / event / config / log / client */
            targetType: string;
            /** @description RFC3339 时间戳 */
            timestamp: string;
        };
        /** @description 分页结果 */
        AuditPage: {
            items: components["schemas"]["AuditEntry"][];
            /** Format: int64 */
            total: number;
        };
        /** @description 查询参数（分页 + 可选过滤） */
        AuditQuery: {
            /** @description 按操作名精确过滤 */
            action?: string | null;
            /** Format: int64 */
            limit?: number;
            /** Format: int64 */
            offset?: number;
            /** @description 按对象类型精确过滤 */
            targetType?: string | null;
        };
        ClientDisconnect: {
            clientId: string;
        };
        /**
         * @description 客户端分组类型
         * @enum {string}
         */
        ClientGroupType: "custom" | "device" | "user" | "webpage";
        /** @description 客户端信息 */
        ClientInfo: {
            connectedAt?: string;
            group?: null | components["schemas"]["ClientGroupType"];
            groupName?: string | null;
            id: string;
            ipAddress: string;
            lastActivityAt?: string;
            metadata?: unknown;
            protocol?: components["schemas"]["ProtocolType"];
            serverId: string;
            socketId: string;
            status?: components["schemas"]["ClientStatus"];
        };
        /**
         * @description 客户端连接状态
         * @enum {string}
         */
        ClientStatus: "connected" | "disconnected";
        /** @description 事件配置 */
        EventConfig: {
            createdAt?: string;
            defaultMessage?: string | null;
            description?: string | null;
            handler?: string | null;
            id?: string;
            isDefault?: boolean;
            name: string;
            pollingEnabled?: boolean;
            /** Format: int64 */
            pollingInterval?: number | null;
            serverId: string;
            status?: components["schemas"]["EventStatus"];
            updatedAt?: string;
        };
        EventId: {
            id: string;
        };
        /**
         * @description 事件运行状态
         * @enum {string}
         */
        EventStatus: "enabled" | "disabled";
        EventToggle: {
            id: string;
            status: string;
        };
        /** @description 心跳配置 */
        HeartbeatConfig: {
            /** @default true */
            enabled: boolean;
            /**
             * Format: int64
             * @default 30000
             */
            pingInterval: number;
            /**
             * Format: int64
             * @default 90000
             */
            pongTimeout: number;
        };
        /**
         * @description HTTP 方法（受管 HTTP 服务的自定义路由可指定）
         * @enum {string}
         */
        HttpMethod: "GET" | "POST" | "PUT" | "DELETE" | "PATCH" | "HEAD" | "OPTIONS" | "ANY";
        /** @description HTTP 自定义路由配置（每个受管 HTTP 服务可配多条） */
        HttpRouteConfig: {
            description?: string | null;
            /** @description 固定事件名；若 None 且路径含 `{event}` 则取路径段；否则取末段 */
            event?: string | null;
            id?: string;
            method?: components["schemas"]["HttpMethod"];
            /** @description 路径，支持 `{event}` 占位符（如 `/{event}`、`/order/{event}`） */
            path?: string;
            routeType?: components["schemas"]["HttpRouteType"];
        };
        /**
         * @description HTTP 路由类型
         *     - Inbound：收消息（body 为 JSON），映射到 on_message
         *     - Stream：SSE 长连接，server→client 单向推送
         * @enum {string}
         */
        HttpRouteType: "inbound" | "stream";
        /** @description IP 黑名单/白名单 */
        IpAccessList: {
            blacklist?: string[];
            whitelist?: string[];
        };
        /** @description 日志条目 */
        LogEntry: {
            clientId?: string | null;
            event?: string;
            id?: string;
            level?: components["schemas"]["LogLevel"];
            message?: string;
            metadata?: unknown;
            serverId?: string | null;
            timestamp?: string;
        };
        /**
         * @description 日志等级
         * @enum {string}
         */
        LogLevel: "DEBUG" | "INFO" | "WARN" | "ERROR";
        MockId: {
            id: string;
        };
        /** @description 头部/查询匹配条件 */
        MockMatchCondition: {
            enabled?: boolean;
            key?: string;
            /** @description 匹配方式：exact / contains / regex / exists */
            matchKind?: string;
            value?: string;
        };
        /** @description Mock 模拟规则 */
        MockRule: {
            description?: string | null;
            enabled?: boolean;
            /** @description 分组（从 Swagger 导入时的 OpenAPI tags；仅前端分组展示用，不影响匹配） */
            group?: string | null;
            id?: string;
            /** @description 请求体匹配（包含子串；空表示不匹配 body） */
            matchBody?: string | null;
            matchHeaders?: components["schemas"]["MockMatchCondition"][];
            matchQuery?: components["schemas"]["MockMatchCondition"][];
            /** @description HTTP 方法（含 ANY） */
            method?: components["schemas"]["HttpMethod"];
            name?: string;
            /** @description 路径模式：精确 `/users`、前缀 `/users/*`、参数 `/users/:id` */
            pathPattern?: string;
            responseBody?: string;
            /** Format: int32 */
            responseDelayMs?: number;
            responseHeaders?: components["schemas"]["MockMatchCondition"][];
            /** Format: int32 */
            responseStatusCode?: number;
        };
        /** @description Mock 服务配置 */
        MockServiceConfig: {
            /** @description 挂载路径（如 `/api/gaop/v1`）；主端口模式下作为前缀；自定义端口模式下作为该端口的根路径 */
            basePath?: string;
            createdAt?: string;
            /**
             * Format: int32
             * @description 自定义端口；None = 挂载到主端口 3080
             */
            customPort?: number | null;
            /** Format: int32 */
            defaultDelayMs?: number;
            /** @description 未匹配规则时返回的响应体 */
            defaultResponseBody?: string;
            /**
             * Format: int32
             * @description 未匹配规则时返回的状态码
             */
            defaultStatusCode?: number;
            description?: string;
            enabled?: boolean;
            id?: string;
            name?: string;
            rules?: components["schemas"]["MockRule"][];
            updatedAt?: string;
        };
        /** @description 持久化配置集合（单 config.json） */
        PersistedConfig: {
            events?: components["schemas"]["EventConfig"][];
            exportedAt?: string;
            mockServices?: components["schemas"]["MockServiceConfig"][];
            scenes?: components["schemas"]["SceneConfig"][];
            servers?: components["schemas"]["ServerConfig"][];
            systemSettings?: components["schemas"]["SystemSettings"];
            version?: string;
            windowConfig?: components["schemas"]["WindowConfig"];
        };
        /**
         * @description 协议类型
         * @enum {string}
         */
        ProtocolType: "websocket" | "socket.io" | "http" | "tcp" | "udp" | "mqtt" | "sse";
        /** @description 场景配置（多服务编排：有序服务组，一键启停） */
        SceneConfig: {
            createdAt?: string;
            description?: string | null;
            enabled?: boolean;
            id?: string;
            name?: string;
            /** @description 服务 ID 有序列表（启动按此顺序、停止逆序） */
            serverIds?: string[];
            updatedAt?: string;
        };
        SceneId: {
            id: string;
        };
        /** @description 场景内单个服务的启停结果 */
        SceneServerResult: {
            error?: string | null;
            serverId: string;
            success: boolean;
        };
        SendBody: {
            clientId?: string | null;
            content?: string | null;
            data?: unknown;
            event: string;
            messageType?: string | null;
            serverId?: string | null;
            targetId?: string | null;
            targetType?: string | null;
        };
        /** @description 服务配置 */
        ServerConfig: {
            /** @default false */
            autoStart: boolean;
            /** @default null */
            certPath: string | null;
            /** @default  */
            createdAt: string;
            /** @default  */
            description: string;
            /**
             * @description HTTP 协议自定义路由（仅 protocol=http 生效；为空则用内置默认：
             *     `POST /{event}` 收消息 + `GET /stream` SSE 推送）
             * @default []
             */
            httpRoutes: components["schemas"]["HttpRouteConfig"][];
            /** @default  */
            id: string;
            /** @default 0.0.0.0 */
            ip: string;
            /** @default null */
            keyPath: string | null;
            /** @default INFO */
            logLevel: components["schemas"]["LogLevel"];
            /**
             * Format: int32
             * @description Mock 默认延迟（ms，未匹配规则时）
             * @default 0
             */
            mockDefaultDelayMs: number;
            /**
             * @description Mock 默认响应体（未匹配规则时返回）
             * @default {"message":"ok"}
             */
            mockDefaultResponseBody: string;
            /**
             * Format: int32
             * @description Mock 默认状态码（未匹配规则时返回）
             * @default 200
             */
            mockDefaultStatusCode: number;
            /**
             * @description 是否在同一端口上同时提供 Mock HTTP 响应（统一路由模式）。
             *     启用后，非 WebSocket 升级的 HTTP 请求将由 Mock 引擎处理（规则匹配 → 模拟响应）。
             *     WebSocket 升级请求（含 `Upgrade: websocket` 头）仍由 Socket 传输层处理。
             *     两者在同一路由 fallback handler 中通过请求类型自动区分，互不干扰。
             * @default false
             */
            mockEnabled: boolean;
            /**
             * @description Mock 规则列表（mock_enabled=true 时生效）；按顺序匹配，首个命中即返回
             * @default []
             */
            mockRules: components["schemas"]["MockRule"][];
            /** @default  */
            name: string;
            /**
             * Format: int32
             * @default 0
             */
            port: number;
            /** @default websocket */
            protocol: components["schemas"]["ProtocolType"];
            /** @default  */
            updatedAt: string;
            /** @default false */
            wssEnabled: boolean;
        };
        ServerId: {
            id: string;
        };
        /** @description 服务运行时状态 */
        ServerRuntime: {
            clientCount?: number;
            error?: string | null;
            id: string;
            /** Format: int64 */
            receivedBytes?: number;
            /** Format: int64 */
            receivedMessages?: number;
            /** Format: int64 */
            reconnectCount?: number;
            /** Format: int64 */
            sentBytes?: number;
            /** Format: int64 */
            sentMessages?: number;
            startedAt?: string | null;
            status?: components["schemas"]["ServerStatus"];
            stoppedAt?: string | null;
            /** Format: int64 */
            totalConnections?: number;
        };
        /**
         * @description 服务运行状态
         * @enum {string}
         */
        ServerStatus: "stopped" | "running" | "error" | "starting" | "stopping";
        SettingsBody: {
            systemSettings?: null | components["schemas"]["SystemSettings"];
            windowConfig?: null | components["schemas"]["WindowConfig"];
        };
        /** @description 系统设置 */
        SystemSettings: {
            autoStart?: boolean;
            heartbeat?: components["schemas"]["HeartbeatConfig"];
            id?: string;
            ipAccess?: components["schemas"]["IpAccessList"];
            /** Format: int64 */
            logRetentionDays?: number;
            /** Format: int64 */
            maxConnectionsPerServer?: number;
            updatedAt?: string;
            wss?: components["schemas"]["WssConfig"];
        };
        /** @description 窗口配置 */
        WindowConfig: {
            /**
             * Format: int32
             * @default 800
             */
            height: number;
            /** @default false */
            maximized: boolean;
            /**
             * Format: int32
             * @default 1280
             */
            width: number;
            /**
             * Format: int32
             * @default null
             */
            x: number | null;
            /**
             * Format: int32
             * @default null
             */
            y: number | null;
        };
        /** @description WSS 配置 */
        WssConfig: {
            certPath?: string;
            enabled?: boolean;
            keyPath?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    audit_logs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    bootstrap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 返回 admin token 与角色（回环自举，免鉴权） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    client_disconnect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientDisconnect"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    client_send: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_clients: {
        parameters: {
            query?: {
                /** @description 按服务 ID 过滤 */
                serverId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_events: {
        parameters: {
            query?: {
                /** @description 按服务 ID 过滤 */
                serverId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    event_add: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventConfig"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    event_remove: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventId"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    event_toggle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventToggle"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    event_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventConfig"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    export_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    import_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersistedConfig"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_logs: {
        parameters: {
            query?: {
                /** @description 按服务 ID 过滤 */
                serverId?: string;
                /** @description 日志级别：DEBUG/INFO/WARN/ERROR */
                level?: string;
                /** @description 关键词过滤 */
                keyword?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logs_clear: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_logs_persisted: {
        parameters: {
            query?: {
                /** @description 每页条数（默认 100，最大 1000） */
                limit?: number;
                /** @description 偏移量 */
                offset?: number;
                /** @description 按服务 ID 过滤 */
                serverId?: string;
                /** @description 日志级别下限：DEBUG/INFO/WARN/ERROR */
                level?: string;
                /** @description 关键词过滤 */
                keyword?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 返回 { total, items } 分页结构 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mock_add: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MockServiceConfig"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mock_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MockId"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mock_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mock_remove: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MockId"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mock_start: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MockId"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mock_stop: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MockId"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mock_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MockServiceConfig"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    scene_add: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SceneConfig"];
            };
        };
        responses: {
            /** @description 添加成功，返回新场景 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    scene_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 场景配置列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    scene_remove: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SceneId"];
            };
        };
        responses: {
            /** @description 删除成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    scene_start: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SceneId"];
            };
        };
        responses: {
            /** @description 启动结果（逐服务） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    scene_stop: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SceneId"];
            };
        };
        responses: {
            /** @description 停止成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    scene_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SceneConfig"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    send_message: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    server_add: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServerConfig"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_server_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    server_remove: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServerId"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    server_restart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServerId"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    server_restart_all: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_server_runtimes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    server_start: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServerId"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    server_start_all: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    server_stop: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServerId"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    server_stop_all: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    server_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServerConfig"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_servers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    save_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
